routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Role;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
|--------------------------------------------------------------------------
| HR Web Routes
|--------------------------------------------------------------------------
*/

Route::group(['middleware'=>'hr'],  function () {

    Route::get('/hr/dashboard', 'HomeController@hr_dashboard')->name('hr.dashboard');

    Route::resource('/hr/user', 'HRUserController');

});

/*
|--------------------------------------------------------------------------
| SuperVisor Web Routes
|--------------------------------------------------------------------------
*/

Route::group(['middleware'=>'supervisor'],  function () {

    Route::get('/supervisor/dashboard', 'HomeController@supervisor_dashboard')->name('supervisor.dashboard');

    Route::get('/supervisor/staff/leave/pending_review', 'SupervisorStaffLeaveController@pending_review')->name('supervisor.leave.pending');

    Route::get('/supervisor/staff/leave/undergoing_review', 'SupervisorStaffLeaveController@undergoing_review')->name('supervisor.leave.undergoing_review');

    Route::get('/supervisor/staff/leave/accepted', 'SupervisorStaffLeaveController@accepted')->name('supervisor.leave.accepted');

    Route::get('/supervisor/staff/leave/rejected', 'SupervisorStaffLeaveController@rejected')->name('supervisor.leave.rejected');

    Route::resource('/supervisor/staff/leave', 'SupervisorStaffLeaveController', ['as' => 'supervisor']);

});



/*
|--------------------------------------------------------------------------
| Staff Web Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware'=>'staff'],  function () {

    Route::get('/staff/dashboard', 'HomeController@staff_dashboard')->name('staff.dashboard');

    Route::resource('/staff/leave', 'StaffLeaveController', ['as' => 'staff']);

});


/*
|--------------------------------------------------------------------------
| Developer Web Routes
|--------------------------------------------------------------------------
|
| These web routes are only for developers. These must be operated
|  only under the supervision of developers. Please comment them after using!
|
*/
 //////////////////////////////////////////////////////////////////////////////////////
 //Create roles when needed, most probably after migrate reset STARTS here
 ////////////////////////////////////////////////////////////////////////////////////

//        Route::get('/createroles', function () {
//
//
//            $role_names = ['HR', 'No role assigned', 'Supervisor', 'Staff'];
//
//            foreach ($role_names as $role_name) {
//
//                $role = new Role;
//
//                $role->name = $role_name;
//
//                $role->save();
//            }
//
//            return "roles created... Please check the data base";
//
//        });

//////////////////////////////////////////////////////////////////////////////////////
//Create roles when needed, most probably after migrate reset ENDS here
////////////////////////////////////////////////////////////////////////////////////
///
///  //////////////////////////////////////////////////////////////////////////////////////
// //Create users when needed, most probably after migrate reset STARTS here
// ////////////////////////////////////////////////////////////////////////////////////
//
//        Route::get('/createusers', function () {
//
//
//            $user_data = [];
//
//            foreach ($role_names as $role_name) {
//
//                $role = new Role;
//
//                $role->name = $role_name;
//
//                $role->save();
//            }
//
//            return "roles created... Please check the data base";
//
//        });
//
////////////////////////////////////////////////////////////////////////////////////////
////Create user when needed, most probably after migrate reset ENDS here
//////////////////////////////////////////////////////////////////////////////////////

app/Leave.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{
    //
    protected $fillable = [

        'user_id', 'status', 'start_date', 'end_date', 'reason', 'photo_id',

    ];

    public function user() {

        return $this->belongsTo('App\User');

    }

    public function photo() {

        return $this->belongsTo('App\Photo');
    }

}

resources/views/staff/leave/create.blade.php
@extends('layouts.staff')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Apply for Leave</div>

                    <div class="card-body">

                        {!! Form::open(['method' => 'POST', 'action'=>'StaffLeaveController@store', 'files'=>true]) !!}

                        <label for="start_date">Start Date:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::date('start_date', null, ['class'=>'form-control', 'id' => 'start_date']) !!}
                        </div>
                        <br>

                        <label for="end_date">End Date:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::date('end_date', null, ['class'=>'form-control', 'id' => 'end_date']) !!}
                        </div>
                        <br>

                        <label for="photo_id">Photo:</label>
                        <div class="input-group">
                            {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
                        </div>
                        <br>

                        <label for="reason">Reason:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::textarea('reason', null, ['class'=>'form-control', 'id' => 'reason']) !!}
                        </div>
                        <br>

                        <div class="input-group">
                            {!! Form::submit('Apply', ['class'=>'btn btn-primary']) !!}
                        </div>

                        {!! Form::close() !!}

                    </div>

                    @include('includes.form_error')

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/staff/leave/edit.blade.php
@extends('layouts.staff')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Leave</div>

                    <div class="card-body">

                        {!! Form::model($leave, ['method' => 'PATCH', 'action'=>['StaffLeaveController@update', $leave->id], 'files'=>true]) !!}

                        <label for="start_date">Start Date:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::date('start_date', null, ['class'=>'form-control', 'id' => 'start_date']) !!}
                        </div>
                        <br>

                        <label for="end_date">End Date:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::date('end_date', null, ['class'=>'form-control', 'id' => 'end_date']) !!}
                        </div>
                        <br>

                        <label for="photo_id">Photo:</label>
                        <div class="input-group">
                            {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
                        </div>
                        <br>

                        <label for="reason">Reason:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::textarea('reason', null, ['class'=>'form-control', 'id' => 'reason']) !!}
                        </div>
                        <br>

                        <div class="input-group">
                            {!! Form::submit('Apply', ['class'=>'btn btn-primary']) !!}
                        </div>

                        {!! Form::close() !!}


                    </div>

                    @include('includes.form_error')

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/staff/leave/index.blade.php
@extends('layouts.staff')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @if(Session::has('leave_deleted'))
                <div class="alert alert-danger">
                    <strong>{{session('leave_deleted')}}!</strong>
                </div>
            @endif

            @if(Session::has('leave_created'))
                <div class="alert alert-success">
                    <strong>{{session('leave_created')}}!</strong>
                </div>
            @endif

            @if(Session::has('leave_updated'))
                <div class="alert alert-info">
                    <strong>{{session('leave_updated')}}!</strong>
                </div>
            @endif
        </div>
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">Leave List</div>
                    <div class="card-body">
                        <div class="alert alert-info" role="alert">
                            Once the status has been set to the following 'Accepted or Rejected', further status changes cannot be made by the staff.
                            <br> When the status is 'Pending review, the staff can make edit the application details'.
                            <br> When the status is 'Undergoing review, the staff cannot edit the application details'.
                        </div>
                          <table class="table table-responsive ">
                            <thead>
                              <tr>
                                <th>ID</th>
                                <th>Status</th>
                                <th>Start Date</th>
                                  <th>End Date</th>
                                  <th>Reason</th>
                                  <th>Photo</th>
                                  <th>Edit</th>
                                  <th>Created at</th>
                                  <th>Updated at</th>
                              </tr>
                            </thead>
                            <tbody>

                            @if($leaves)

                                @foreach($leaves as $leave)

                                    <tr>
                                        <td>{{$leave->id}}</td>
                                        <td>
                                            @if($leave->status == 0)
                                                    <div class="alert-danger"> Rejected </div>
                                                @elseif($leave->status == 1)
                                                    <div class="alert-success"> Accepted </div>
                                                @elseif($leave->status == 2)
                                                    <div class="alert-info"> Undergoing Review </div>
                                                @elseif($leave->status == 3)
                                                    <div class="alert-warning"> Pending Review </div>
                                            @endif
                                        </td>
                                        <td>{{$leave->start_date}}</td>
                                        <td>{{$leave->end_date}}</td>
                                        <td>{{$leave->reason}}</td>
                                        <td>
                                            <img height="50" src="{{$leave->photo ? $leave->photo->file : 'http://placehold.it/400x400'}}">
                                        </td>
                                        <td>
                                            @if($leave->status == 0 || $leave->status == 1 || $leave->status == 2)
                                                Edit Not Available
                                            @else
                                                <a href="{{route('staff.leave.edit', $leave->id)}}"><button class="btn btn-primary">Edit</button></a>
                                            @endif
                                        </td>
                                        <td>{{$leave->created_at->diffForHumans()}}</td>
                                        <td>{{$leave->updated_at->diffForHumans()}}</td>
                                    </tr>

                                @endforeach

                            @endif


                            </tbody>
                          </table>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection