routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Role;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

/*
|--------------------------------------------------------------------------
| HR Web Routes
|--------------------------------------------------------------------------
*/

Route::group(['middleware'=>'hr'],  function () {

    Route::get('/hr/dashboard', 'HomeController@hr_dashboard')->name('hr.dashboard');

    Route::resource('/hr/user', 'HRUserController');

});

/*
|--------------------------------------------------------------------------
| SuperVisor Web Routes
|--------------------------------------------------------------------------
*/

Route::group(['middleware'=>'supervisor'],  function () {

    Route::get('/supervisor/dashboard', 'HomeController@supervisor_dashboard')->name('supervisor.dashboard');

    Route::get('/supervisor/staff/leave/pending_review', 'SupervisorStaffLeaveController@pending_review')->name('supervisor.leave.pending');

    Route::get('/supervisor/staff/leave/undergoing_review', 'SupervisorStaffLeaveController@undergoing_review')->name('supervisor.leave.undergoing_review');

    Route::get('/supervisor/staff/leave/accepted', 'SupervisorStaffLeaveController@accepted')->name('supervisor.leave.accepted');

    Route::get('/supervisor/staff/leave/rejected', 'SupervisorStaffLeaveController@rejected')->name('supervisor.leave.rejected');

    Route::resource('/supervisor/staff/leave', 'SupervisorStaffLeaveController', ['as' => 'supervisor']);

});



/*
|--------------------------------------------------------------------------
| Staff Web Routes
|--------------------------------------------------------------------------
*/
Route::group(['middleware'=>'staff'],  function () {

    Route::get('/staff/dashboard', 'HomeController@staff_dashboard')->name('staff.dashboard');

    Route::resource('/staff/leave', 'StaffLeaveController', ['as' => 'staff']);

});


/*
|--------------------------------------------------------------------------
| Developer Web Routes
|--------------------------------------------------------------------------
|
| These web routes are only for developers. These must be operated
|  only under the supervision of developers. Please comment them after using!
|
*/
 //////////////////////////////////////////////////////////////////////////////////////
 //Create roles when needed, most probably after migrate reset STARTS here
 ////////////////////////////////////////////////////////////////////////////////////

//        Route::get('/createroles', function () {
//
//
//            $role_names = ['HR', 'No role assigned', 'Supervisor', 'Staff'];
//
//            foreach ($role_names as $role_name) {
//
//                $role = new Role;
//
//                $role->name = $role_name;
//
//                $role->save();
//            }
//
//            return "roles created... Please check the data base";
//
//        });

//////////////////////////////////////////////////////////////////////////////////////
//Create roles when needed, most probably after migrate reset ENDS here
////////////////////////////////////////////////////////////////////////////////////
///
///  //////////////////////////////////////////////////////////////////////////////////////
// //Create users when needed, most probably after migrate reset STARTS here
// ////////////////////////////////////////////////////////////////////////////////////
//
//        Route::get('/createusers', function () {
//
//
//            $user_data = [];
//
//            foreach ($role_names as $role_name) {
//
//                $role = new Role;
//
//                $role->name = $role_name;
//
//                $role->save();
//            }
//
//            return "roles created... Please check the data base";
//
//        });
//
////////////////////////////////////////////////////////////////////////////////////////
////Create user when needed, most probably after migrate reset ENDS here
//////////////////////////////////////////////////////////////////////////////////////

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'status', 'photo_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role() {

        return $this->belongsTo('App\Role');

    }

    public function photo() {

        return $this->belongsTo('App\Photo');


    }

    public function leaves() {

        return $this->hasMany('App\Leave');

    }

    public function isSupervisor() {

        if($this->role->name == 'Supervisor' && $this->status == 1) {

            return true;
        }

        return false;

    }

    public function isHr() {

        if($this->role->name == 'HR'  && $this->status == 1) {

            return true;
        }

        return false;

    }

    public function isStaff() {

        if($this->role->name == 'Staff' && $this->status == 1) {

            return true;
        }

        return false;

    }

}

resources/views/hr/user/create.blade.php
@extends('layouts.hr')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create Employee</div>

                    <div class="card-body">

                        {!! Form::open(['method' => 'POST', 'action'=>'HRUserController@store', 'files'=>true]) !!}

                        <label for="name">Name:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::text('name', null, ['class'=>'form-control', 'id' => 'name', 'placeholder' => 'Name']) !!}
                        </div>
                        <br>

                        <label for="email">Email:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::email('email', null, ['class'=>'form-control', 'id' => 'email', 'placeholder' => 'Email']) !!}
                        </div>
                        <br>

                        <label for="password">Password:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::password('password', ['class'=>'form-control', 'id' => 'password', 'placeholder' => 'Password']) !!}
                        </div>
                        <br>

                        <label for="role_id">Role:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::select('role_id', array('' => 'Select a role') + $roles, 'null', ['class'=>'form-control', 'id' => 'role_id']) !!}
                        </div>
                        <br>

                        <label for="status">Status:</label>
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                            {!! Form::select('status', array(''=>'Select status', 1 => 'Active', 0 => 'Not Active'), null, ['class'=>'form-control', 'id' => 'status']) !!}
                        </div>
                        <br>

                        <label for="photo_id">Photo:</label>
                        <div class="input-group">
                            {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
                        </div>
                        <br>

                        <div class="input-group">
                            {!! Form::submit('Create User', ['class'=>'btn btn-primary']) !!}
                        </div>

                        {!! Form::close() !!}



                    </div>
                </div>
                <br>

                @include('includes.form_error')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/hr/user/edit.blade.php
@extends('layouts.hr')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit Employee</div>
                    <div class="card-body">

                        <div class="">
                            <img height="100px" src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" alt="" class="img-responsive img-rounded">
                        </div>

                        <div class="">

                            {!! Form::model($user, ['method' => 'PATCH', 'action'=>['HRUserController@update', $user->id], 'files'=>true]) !!}

                            <label for="name">Name:</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                {!! Form::text('name', null, ['class'=>'form-control', 'id' => 'name', 'placeholder' => 'Name']) !!}
                            </div>
                            <br>

                            <label for="email">Email:</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                {!! Form::email('email', null, ['class'=>'form-control', 'id' => 'email', 'placeholder' => 'Email']) !!}
                            </div>
                            <br>

                            <label for="password">Password: (Leave blank for not changing password)</label>
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                {!! Form::password('password', ['class'=>'form-control', 'id' => 'password', 'placeholder' => 'Password']) !!}
                            </div>
                            <br>

                            @if(($user->role->name == 'HR') )

                                <label for="role_id">Role:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    {!! Form::select('role_id', array('1'=>'HR'), 'HR', ['class'=>'form-control', 'id' => 'role_id',]) !!}
                                </div>
                                <br>

                                <label for="status">Status:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    {!! Form::select('status', array(1 => 'Active'), null, ['class'=>'form-control', 'id' => 'status']) !!}
                                </div>
                                <br>

                            @else

                                <label for="role_id">Role:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    {!! Form::select('role_id', array(''=>'Select Role') + $roles, $user->role_id, ['class'=>'form-control', 'id' => 'role_id']) !!}
                                </div>
                                <br>

                                <label for="status">Status:</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    {!! Form::select('status', array(''=>'Select status', 1 => 'Active', 0 => 'Not Active'), null, ['class'=>'form-control', 'id' => 'status']) !!}
                                </div>
                                <br>

                            @endif

                            <label for="photo_id">Photo:</label>
                            <div class="input-group">
                                {!! Form::file('photo_id', null, ['class'=>'form-control']) !!}
                            </div>
                            <br>

                            <div class="col-sm-3">
                                <div class="input-group">
                                    {!! Form::submit('Update User', ['class'=>'btn btn-primary']) !!}
                                </div>
                            </div>

                            {!! Form::close() !!}
                            <br>

                        </div>

                        <div class="">

                            @include('includes.form_error')

                        </div>
                    </div>
                </div><!-- card body close -->
                <br>

                    @if((Auth::user()->email != $user->email) && (Auth::user()->role_id < $user->role_id) )
                    <div class="card">
                        <div class="card-header">

                            {{Auth::user()->role_id}} {{ $user->role_id }}

                            {!! Form::open(['method' => 'DELETE', 'action'=>['HRUserController@destroy', $user->id]]) !!}

                            <div class="input-group">
                                {!! Form::submit('Delete User', ['class'=>'btn btn-danger']) !!}
                            </div>

                            {!! Form::close() !!}
                        </div>
                    </div>
                @endif

            </div>
        </div>
    </div>
@endsection

resources/views/hr/user/index.blade.php
@extends('layouts.hr')

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            @if(Session::has('user_deleted'))
                <div class="alert alert-danger">
                    <strong>{{session('user_deleted')}}!</strong>
                </div>
            @endif

            @if(Session::has('user_created'))
                <div class="alert alert-success">
                    <strong>{{session('user_created')}}!</strong>
                </div>
            @endif

            @if(Session::has('user_updated'))
                <div class="alert alert-info">
                    <strong>{{session('user_updated')}}!</strong>
                </div>
            @endif

            <div class="">
                <div class="card">
                    <div class="card-header">Employee List</div>

                    <table class="table table-responsive">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Photo</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Role</th>
                            <th>Created</th>
                            <th>Updated</th>
                            <th>Edit</th>
                        </tr>
                        </thead>
                        <tbody>

                        @if($users)

                            @foreach($users as $user)
                                <tr>
                                    <td>{{$user->id}}</td>
                                    <td><img height="50" src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" > </td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->status == 1 ? 'Active' : 'Not Active'}}</td>
                                    <td>{{$user->role->name}}</td>
                                    <td>{{$user->created_at->diffForHumans()}}</td>
                                    <td>{{$user->updated_at->diffForHumans()}}</td>
                                    <td><a href="{{route('user.edit', $user->id)}}"><button class="btn btn-primary">Edit</button></a></td>
                                </tr>

                            @endforeach

                        @endif
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection